# DORA Metrics for Lead Time Only

## Env

**Output:**
- Working Kernel
- Loaded python libraries

In [1]:
print("Kernel is working.")

Kernel is working.

In [2]:
from dash import dcc
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

## Data Ingestion

**Output:** pandas dataframe *df_lead*.

In [3]:
# Useful reference: <https://pandas.pydata.org/docs/getting_started/intro_tutorials/09_timeseries.html>
raw_file_path = '/home/lnx_workspaces/bpp_projects/bpp_module2_project/doraview/data/json/change_lead_time.json'

# Try reading with explicit encoding and error handling
try:
    df_lead = pd.read_json(raw_file_path, encoding='utf-8', convert_dates=["deployed_at"]).sort_values(by=["commit_time"])
    print("\nDataframe info:")
    print(df_lead.info())
    print("\nFirst 5 rows:")
    print(df_lead.head())
except Exception as e:
    print(f"Error: {str(e)}")

Dataframe info:
<class 'pandas.core.frame.DataFrame'>
Index: 44 entries, 28 to 5
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   change_id        44 non-null     object
 1   application_id   44 non-null     object
 2   commit_id        44 non-null     object
 3   commit_time      44 non-null     datetime64[ns, UTC]
 4   deploy_id        44 non-null     object
 5   deploy_time      44 non-null     datetime64[ns, UTC]
 6   lead_time_hours  44 non-null     int64
dtypes: datetime64[ns, UTC](2), int64(1), object(4)
memory usage: 2.8+ KB
None

First 5 rows:
       change_id application_id commit_id               commit_time  \
28  chg_a5f8cfaf         app003    bdc28e 2025-07-01 08:09:00+00:00
35  chg_dd68cbb5         app003    4bb702 2025-07-02 00:37:00+00:00
8   chg_8f6ee15b         app001    ca3e35 2025-07-07 13:35:00+00:00
11  chg_90d9652e         app001    cd7d15 2025-07-10 17:58:00+00:00
40  chg_22754b79         app003    00540b 2025-07-13 02:40:00+00:00

      deploy_id               deploy_time  lead_time_hours
28  df_c5a7c423 2025-07-02 16:09:00+00:00               32
35  df_15eb7c8c 2025-07-02 10:37:00+00:00               10
8   df_295ed3f1 2025-07-07 16:35:00+00:00                3
11  df_83590aea 2025-07-13 00:58:00+00:00               55
40  df_d6b6cdf5 2025-07-16 01:40:00+00:00               71

## Data Manipulation

**Output:** Updates to pandas data frame *df_lead* for use by figures.
- New aggregated month datetime column.
- New Moving Average columns for plotting (SMA, EMA, CMA)

In [4]:
# Add new row and quater columns
df_lead["commit_month"] = df_lead["commit_time"].dt.month
df_lead["deploy_month"] = df_lead["deploy_time"].dt.month

df_lead.sort_values(by=["commit_time"], inplace=True)

df_lead.head(100)

,change_id,application_id,commit_id,commit_time,deploy_id,deploy_time,lead_time_hours,commit_month,deploy_month
28,chg_a5f8cfaf,app003,bdc28e,2025-07-01 08:09:00+00:00,df_c5a7c423,2025-07-02 16:09:00+00:00,32,7,7
35,chg_dd68cbb5,app003,4bb702,2025-07-02 00:37:00+00:00,df_15eb7c8c,2025-07-02 10:37:00+00:00,10,7,7
8,chg_8f6ee15b,app001,ca3e35,2025-07-07 13:35:00+00:00,df_295ed3f1,2025-07-07 16:35:00+00:00,3,7,7
11,chg_90d9652e,app001,cd7d15,2025-07-10 17:58:00+00:00,df_83590aea,2025-07-13 00:58:00+00:00,55,7,7
40,chg_22754b79,app003,00540b,2025-07-13 02:40:00+00:00,df_d6b6cdf5,2025-07-16 01:40:00+00:00,71,7,7
12,chg_cfd655f7,app001,e65c95,2025-07-13 05:43:00+00:00,df_f8b93c0a,2025-07-15 07:43:00+00:00,50,7,7
16,chg_1918cc5e,app002,2e6951,2025-07-18 22:43:00+00:00,df_a29aae73,2025-07-19 08:43:00+00:00,10,7,7
14,chg_db7dbdff,app002,3d91ec,2025-07-20 13:15:00+00:00,df_8966166b,2025-07-22 04:15:00+00:00,39,7,7
2,chg_5e11ee73,app001,966c88,2025-07-25 05:08:00+00:00,df_45056a55,2025-07-27 12:08:00+00:00,55,7,7
10,chg_2c869d04,app001,4c513e,2025-07-27 19:14:00+00:00,df_325b9203,2025-07-30 06:14:00+00:00,59,7,7
4,chg_4f2d1c11,app001,fb3132,2025-07-29 01:29:00+00:00,df_9ddc9087,2025-07-29 03:29:00+00:00,2,7,7
43,chg_ef38d368,app003,caa87e,2025-07-29 22:50:00+00:00,df_53f88664,2025-08-01 17:50:00+00:00,67,7,8
38,chg_49a056ac,app003,ba75c2,2025-07-30 15:14:00+00:00,df_6d11b196,2025-07-31 19:14:00+00:00,28,7,7
15,chg_7b9765c2,app002,8e49b5,2025-07-31 00:16:00+00:00,df_e2070f8a,2025-08-02 05:16:00+00:00,53,7,8
18,chg_08bb612e,app002,162a37,2025-07-31 21:31:00+00:00,df_42d14791,2025-08-02 23:31:00+00:00,50,7,8
42,chg_fffb86b6,app003,c08152,2025-08-02 22:25:00+00:00,df_f07e8344,2025-08-03 21:25:00+00:00,23,8,8
31,chg_f30ed218,app003,ed408b,2025-08-03 17:21:00+00:00,df_cf9778b0,2025-08-04 12:21:00+00:00,19,8,8
7,chg_38561156,app001,5f978b,2025-08-05 11:03:00+00:00,df_3ad908f6,2025-08-07 03:03:00+00:00,40,8,8
27,chg_ce8bba64,app003,f8eecd,2025-08-06 07:01:00+00:00,df_d7800254,2025-08-06 14:01:00+00:00,7,8,8
1,chg_07c1430b,app001,fe117b,2025-08-06 18:06:00+00:00,df_952faf50,2025-08-07 11:06:00+00:00,17,8,8
9,chg_4900aa6e,app001,0b2192,2025-08-07 06:38:00+00:00,df_1df285b7,2025-08-09 09:38:00+00:00,51,8,8
26,chg_74ac1d7b,app003,c1afbb,2025-08-07 07:43:00+00:00,df_b500d7ed,2025-08-07 15:43:00+00:00,8,8,8
6,chg_b8d6bfe0,app001,87ff9e,2025-08-09 22:09:00+00:00,df_0721d117,2025-08-11 14:09:00+00:00,40,8,8
36,chg_92e91ad0,app003,6f38ad,2025-08-12 18:23:00+00:00,df_b1681d57,2025-08-13 00:23:00+00:00,6,8,8
29,chg_93e87bc8,app003,2e9095,2025-08-14 01:17:00+00:00,df_5bb38c81,2025-08-15 09:17:00+00:00,32,8,8
3,chg_e5c3ae12,app001,5cd1f5,2025-08-14 20:24:00+00:00,df_4a4be475,2025-08-16 06:24:00+00:00,34,8,8
33,chg_0f136a34,app003,065054,2025-08-15 02:54:00+00:00,df_f5c0995f,2025-08-15 23:54:00+00:00,21,8,8
25,chg_a70cc5c5,app003,6fd64d,2025-08-15 04:50:00+00:00,df_ae125801,2025-08-18 04:50:00+00:00,72,8,8
19,chg_47d6ca53,app002,ba290a,2025-08-16 13:08:00+00:00,df_883f7d05,2025-08-16 16:08:00+00:00,3,8,8
20,chg_93daa1e0,app002,9b4aca,2025-08-17 05:59:00+00:00,df_f6f4c236,2025-08-19 03:59:00+00:00,46,8,8
24,chg_2c7f2095,app002,1fdf33,2025-08-18 09:50:00+00:00,df_58d098e5,2025-08-19 20:50:00+00:00,35,8,8
39,chg_e1229847,app003,28f976,2025-08-23 10:42:00+00:00,df_90e28045,2025-08-25 04:42:00+00:00,42,8,8
32,chg_bc8efe2b,app003,0e6f93,2025-08-25 00:06:00+00:00,df_e3245815,2025-08-27 21:06:00+00:00,69,8,8
0,chg_4895de12,app001,edea2a,2025-08-30 05:05:00+00:00,df_55eeff30,2025-08-31 02:05:00+00:00,21,8,8
23,chg_d23cf279,app002,973452,2025-09-02 13:30:00+00:00,df_33cfc06f,2025-09-03 22:30:00+00:00,33,9,9
21,chg_c838fa38,app002,975ece,2025-09-02 21:34:00+00:00,df_b864e01d,2025-09-03 12:34:00+00:00,15,9,9
13,chg_bf7c7ec3,app001,d0ecdc,2025-09-04 01:04:00+00:00,df_b1bb652d,2025-09-05 06:04:00+00:00,29,9,9
22,chg_51e88a14,app002,b201f8,2025-09-09 09:26:00+00:00,df_df253d66,2025-09-11 08:26:00+00:00,47,9,9
34,chg_1dd8ed72,app003,3ba359,2025-09-16 11:07:00+00:00,df_6a468578,2025-09-17 18:07:00+00:00,31,9,9
17,chg_efb0d03d,app002,e6fbba,2025-09-17 03:46:00+00:00,df_5fe481e2,2025-09-17 17:46:00+00:00,14,9,9
41,chg_796258a3,app003,b7573d,2025-09-24 01:22:00+00:00,df_a72a3a42,2025-09-27 01:22:00+00:00,72,9,9
30,chg_8ee72d04,app003,e860e2,2025-09-26 06:19:00+00:00,df_9e76efaf,2025-09-27 14:19:00+00:00,32,9,9
37,chg_8da2fc08,app003,8fdbe1,2025-09-27 20:20:00+00:00,df_d091108b,2025-09-29 03:20:00+00:00,31,9,9
5,chg_4514f35b,app001,ade602,2025-09-27 21:01:00+00:00,df_09f6a4a8,2025-09-30 17:01:00+00:00,68,9,9

In [19]:
# Add moving average column
# https://www.geeksforgeeks.org/pandas/how-to-calculate-moving-average-in-a-pandas-dataframe/

# Simple Moving Average
df_lead["SMA"] = df_lead["lead_time_hours"].rolling(window=30).mean()

# Exponential Moving Average
df_lead["EMA"] = df_lead["lead_time_hours"].ewm(span=30, adjust=True).mean()

# Cumulative Moving Average
df_lead["CMA"] = df_lead["lead_time_hours"].expanding().mean()

df_lead.sort_values(by=["commit_time"], inplace=True)

df_lead.head(100)

,change_id,application_id,commit_id,commit_time,deploy_id,deploy_time,lead_time_hours,commit_month,deploy_month,SMA,EMA,CMA
28,chg_a5f8cfaf,app003,bdc28e,2025-07-01 08:09:00+00:00,df_c5a7c423,2025-07-02 16:09:00+00:00,32,7,7,NaN,32.000000,32.000000
35,chg_dd68cbb5,app003,4bb702,2025-07-02 00:37:00+00:00,df_15eb7c8c,2025-07-02 10:37:00+00:00,10,7,7,NaN,20.633333,21.000000
8,chg_8f6ee15b,app001,ca3e35,2025-07-07 13:35:00+00:00,df_295ed3f1,2025-07-07 16:35:00+00:00,3,7,7,NaN,14.359496,15.000000
11,chg_90d9652e,app001,cd7d15,2025-07-10 17:58:00+00:00,df_83590aea,2025-07-13 00:58:00+00:00,55,7,7,NaN,25.557436,25.000000
40,chg_22754b79,app003,00540b,2025-07-13 02:40:00+00:00,df_d6b6cdf5,2025-07-16 01:40:00+00:00,71,7,7,NaN,35.896720,34.200000
12,chg_cfd655f7,app001,e65c95,2025-07-13 05:43:00+00:00,df_f8b93c0a,2025-07-15 07:43:00+00:00,50,7,7,NaN,38.655804,36.833333
16,chg_1918cc5e,app002,2e6951,2025-07-18 22:43:00+00:00,df_a29aae73,2025-07-19 08:43:00+00:00,10,7,7,NaN,33.699596,33.000000
14,chg_db7dbdff,app002,3d91ec,2025-07-20 13:15:00+00:00,df_8966166b,2025-07-22 04:15:00+00:00,39,7,7,NaN,34.526650,33.750000
2,chg_5e11ee73,app001,966c88,2025-07-25 05:08:00+00:00,df_45056a55,2025-07-27 12:08:00+00:00,55,7,7,NaN,37.453374,36.111111
10,chg_2c869d04,app001,4c513e,2025-07-27 19:14:00+00:00,df_325b9203,2025-07-30 06:14:00+00:00,59,7,7,NaN,40.309502,38.400000
4,chg_4f2d1c11,app001,fb3132,2025-07-29 01:29:00+00:00,df_9ddc9087,2025-07-29 03:29:00+00:00,2,7,7,NaN,35.554864,35.090909
43,chg_ef38d368,app003,caa87e,2025-07-29 22:50:00+00:00,df_53f88664,2025-08-01 17:50:00+00:00,67,7,8,NaN,39.238057,37.750000
38,chg_49a056ac,app003,ba75c2,2025-07-30 15:14:00+00:00,df_6d11b196,2025-07-31 19:14:00+00:00,28,7,7,NaN,37.987531,37.000000
15,chg_7b9765c2,app002,8e49b5,2025-07-31 00:16:00+00:00,df_e2070f8a,2025-08-02 05:16:00+00:00,53,7,8,NaN,39.583434,38.142857
18,chg_08bb612e,app002,162a37,2025-07-31 21:31:00+00:00,df_42d14791,2025-08-02 23:31:00+00:00,50,7,8,NaN,40.646351,38.933333
42,chg_fffb86b6,app003,c08152,2025-08-02 22:25:00+00:00,df_f07e8344,2025-08-03 21:25:00+00:00,23,8,8,NaN,38.910825,37.937500
31,chg_f30ed218,app003,ed408b,2025-08-03 17:21:00+00:00,df_cf9778b0,2025-08-04 12:21:00+00:00,19,8,8,NaN,37.016674,36.823529
7,chg_38561156,app001,5f978b,2025-08-05 11:03:00+00:00,df_3ad908f6,2025-08-07 03:03:00+00:00,40,8,8,NaN,37.292052,37.000000
27,chg_ce8bba64,app003,f8eecd,2025-08-06 07:01:00+00:00,df_d7800254,2025-08-06 14:01:00+00:00,7,8,8,NaN,34.571525,35.421053
1,chg_07c1430b,app001,fe117b,2025-08-06 18:06:00+00:00,df_952faf50,2025-08-07 11:06:00+00:00,17,8,8,NaN,33.032359,34.500000
9,chg_4900aa6e,app001,0b2192,2025-08-07 06:38:00+00:00,df_1df285b7,2025-08-09 09:38:00+00:00,51,8,8,NaN,34.570720,35.285714
26,chg_74ac1d7b,app003,c1afbb,2025-08-07 07:43:00+00:00,df_b500d7ed,2025-08-07 15:43:00+00:00,8,8,8,NaN,32.342791,34.045455
6,chg_b8d6bfe0,app001,87ff9e,2025-08-09 22:09:00+00:00,df_0721d117,2025-08-11 14:09:00+00:00,40,8,8,NaN,32.972664,34.304348
36,chg_92e91ad0,app003,6f38ad,2025-08-12 18:23:00+00:00,df_b1681d57,2025-08-13 00:23:00+00:00,6,8,8,NaN,30.792607,33.125000
29,chg_93e87bc8,app003,2e9095,2025-08-14 01:17:00+00:00,df_5bb38c81,2025-08-15 09:17:00+00:00,32,8,8,NaN,30.888628,33.080000
3,chg_e5c3ae12,app001,5cd1f5,2025-08-14 20:24:00+00:00,df_4a4be475,2025-08-16 06:24:00+00:00,34,8,8,NaN,31.132409,33.115385
33,chg_0f136a34,app003,065054,2025-08-15 02:54:00+00:00,df_f5c0995f,2025-08-15 23:54:00+00:00,21,8,8,NaN,30.349353,32.666667
25,chg_a70cc5c5,app003,6fd64d,2025-08-15 04:50:00+00:00,df_ae125801,2025-08-18 04:50:00+00:00,72,8,8,NaN,33.527636,34.071429
19,chg_47d6ca53,app002,ba290a,2025-08-16 13:08:00+00:00,df_883f7d05,2025-08-16 16:08:00+00:00,3,8,8,NaN,31.225278,33.000000
20,chg_93daa1e0,app002,9b4aca,2025-08-17 05:59:00+00:00,df_f6f4c236,2025-08-19 03:59:00+00:00,46,8,8,33.433333,32.327552,33.433333
24,chg_2c7f2095,app002,1fdf33,2025-08-18 09:50:00+00:00,df_58d098e5,2025-08-19 20:50:00+00:00,35,8,8,33.533333,32.524940,33.483871
39,chg_e1229847,app003,28f976,2025-08-23 10:42:00+00:00,df_90e28045,2025-08-25 04:42:00+00:00,42,8,8,34.600000,33.218291,33.750000
32,chg_bc8efe2b,app003,0e6f93,2025-08-25 00:06:00+00:00,df_e3245815,2025-08-27 21:06:00+00:00,69,8,8,36.800000,35.814187,34.818182
0,chg_4895de12,app001,edea2a,2025-08-30 05:05:00+00:00,df_55eeff30,2025-08-31 02:05:00+00:00,21,8,8,35.666667,34.748009,34.411765
23,chg_d23cf279,app002,973452,2025-09-02 13:30:00+00:00,df_33cfc06f,2025-09-03 22:30:00+00:00,33,9,9,34.400000,34.623136,34.371429
21,chg_c838fa38,app002,975ece,2025-09-02 21:34:00+00:00,df_b864e01d,2025-09-03 12:34:00+00:00,15,9,9,33.233333,33.230942,33.833333
13,chg_bf7c7ec3,app001,d0ecdc,2025-09-04 01:04:00+00:00,df_b1bb652d,2025-09-05 06:04:00+00:00,29,9,9,33.866667,32.932689,33.702703
22,chg_51e88a14,app002,b201f8,2025-09-09 09:26:00+00:00,df_df253d66,2025-09-11 08:26:00+00:00,47,9,9,34.133333,33.918448,34.052632
34,chg_1dd8ed72,app003,3ba359,2025-09-16 11:07:00+00:00,df_6a468578,2025-09-17 18:07:00+00:00,31,9,9,33.333333,33.715070,33.974359
17,chg_efb0d03d,app002,e6fbba,2025-09-17 03:46:00+00:00,df_5fe481e2,2025-09-17 17:46:00+00:00,14,9,9,31.833333,32.348252,33.475000
41,chg_796258a3,app003,b7573d,2025-09-24 01:22:00+00:00,df_a72a3a42,2025-09-27 01:22:00+00:00,72,9,9,34.166667,35.084085,34.414634
30,chg_8ee72d04,app003,e860e2,2025-09-26 06:19:00+00:00,df_9e76efaf,2025-09-27 14:19:00+00:00,32,9,9,33.000000,34.872243,34.357143
37,chg_8da2fc08,app003,8fdbe1,2025-09-27 20:20:00+00:00,df_d091108b,2025-09-29 03:20:00+00:00,31,9,9,33.100000,34.607368,34.279070
5,chg_4514f35b,app001,ade602,2025-09-27 21:01:00+00:00,df_09f6a4a8,2025-09-30 17:01:00+00:00,68,9,9,33.600000,36.882691,35.045455

## Figures

### ChatGPT - Lead Time for Changes (LTFC)

**Best Graph Type:** Line Chart with moving average.

**Why:** Lead time is duration measured from commit → deploy.

**It is inherently a time-series, so a line graph best shows:**

- Whether lead times are improving
- How stable or volatile the engineering process is
- The impact of process changes (e.g., new CI/CD pipeline)

**Optional secondary views:**

- Box and Whisker Plot for showing distribution of lead times (median, IQR, outliers)
- Scatter Plot per change, with trend line
- Histogram to show distribution of durations

These alternatives help illustrate variability, which is important in discussing reliability.

### Styling

['#636EFA', # the plotly blue you can see above
 '#EF553B',
 '#00CC96',
 '#AB63FA',
 '#FFA15A',
 '#19D3F3',
 '#FF6692',
 '#B6E880',
 '#FF97FF',
 '#FECB52']

### Scatter Plot

In [6]:
# https://plotly.com/python/line-and-scatter/
fig_lead_scatter = px.scatter(
	data_frame=df_lead,
	title="Lead Time for Changes Scatter Plot",	# Label for the figure.
	x="commit_time",							# Column for use on x-axis
	y="lead_time_hours",							# Column for use on y-axis
	color="application_id",					# Column for use on color grouping
	)

fig_lead_scatter.show()

### Simple Moving Average Plot

In [7]:
fig_lead_line_sma = px.line(
	data_frame=df_lead,
	title="Lead Time for Changes with EMA Line Plot",	# Label for the figure.
	x="commit_time",							# Column for use on x-axis
	y="SMA",							# Column for use on y-axis
	color="application_id",					# Column for use on color grouping
	)

fig_lead_line_sma.show()

### Exponential Moving Average Plot

In [20]:
fig_lead_line_ema = px.line(
	data_frame=df_lead,
	title="Lead Time for Changes with EMA Line Plot",	# Label for the figure.
	x="commit_time",							# Column for use on x-axis
	y="EMA",							# Column for use on y-axis
	color="application_id",					# Column for use on color grouping
	)

fig_lead_line_ema.show()

### Cumulative Moving Average Plot

In [9]:
fig_lead_line_cma = px.line(
	data_frame=df_lead,
	title="Lead Time for Changes with EMA Line Plot",	# Label for the figure.
	x="commit_time",							# Column for use on x-axis
	y="CMA",							# Column for use on y-axis
	color="application_id",					# Column for use on color grouping
	)

fig_lead_line_cma.show()

### Dual Scatter & MA with "traces"

In [21]:
# https://stackoverflow.com/questions/74520782/plotly-express-overlay-two-line-graphs
fig_lead_scat_trace = px.scatter(
	data_frame=df_lead,
	title="Lead Time for Changes Scatter Plot",	# Label for the figure.
	x="commit_time",							# Column for use on x-axis
	y="lead_time_hours",							# Column for use on y-axis
	color="application_id",					# Column for use on color grouping
	)


fig_lead_ema_trace = px.line(
	data_frame=df_lead,
	title="Lead Time for Changes with EMA Line Plot",	# Label for the figure.
	x="commit_time",							# Column for use on x-axis
	y="EMA",							# Column for use on y-axis
	color="application_id",					# Column for use on color grouping
	)

fig_lead_scat_trace.add_traces(
	list(fig_lead_ema_trace.select_traces())
)


fig_lead_scat_trace.show()